# Generated by Django 5.2.1 on 2025-05-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('sci', 'Sci-Fi')], max_length=20)),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cover', models.ImageField(upload_to='covers/')),
            ],
        ),
    ]
